### ISSUE TITLE
Song Export Not currently functioning...

### ISSUE THREAD

**Issue by Bonboon229** [beanieaxolotl/shinen-gax-python#16]
Gives me an error as seen below

Traceback (most recent call last):
  File "C:\Users\gojigoodra\Downloads\shinen-gax-python-main\gax_song_export.py", line 86, in <module>
    setup_GAX(music_path)
  File "C:\Users\gojigoodra\Downloads\shinen-gax-python-main\gax_song_export.py", line 56, in setup_GAX
    gax_obj = unpack_GAX_file(gax_file)
  File "C:\Users\gojigoodra\Downloads\shinen-gax-python-main\libs\shinen_gax.py", line 927, in unpack_GAX_file
    raise ValueError("Unsupported format")
ValueError: Unsupported format

**Comment by beanieaxolotl** [comment]
What file were you using that gave you this error?

**Comment by Bonboon229** [comment]
Pretty much every GAX confirmed rom I threw at it

**Comment by beanieaxolotl** [comment]
The script in question is meant for .gax files (as in the music data blob), not for Game Boy Advance ROMs. this could be a feature in the future, though.

**Comment by Bonboon229** [comment]
Also thank you oh so kindly for getting on this so quickly!
I'll report back if I discover more errors/bugs/ect

**Comment by Bonboon229** [comment]
Forgive me for reopening btw, but how do I go about decompiling to a .gax file?
