### ISSUE TITLE
Oop, found another bug

### ISSUE THREAD

**Issue by Bonboon229** [beanieaxolotl/shinen-gax-python#17]
Traceback (most recent call last):
  File "C:\Users\gojigoodra\Downloads\shinen-gax-python-main\gaxripper_v2.py", line 167, in <module>
    NAX_obj = gax.pack_GAX_file(gax_object, compile_object=False)
  File "C:\Users\gojigoodra\Downloads\shinen-gax-python-main\libs\shinen_gax.py", line 1195, in pack_GAX_file
    packed_instrument = instrument.pack_instrument()
  File "C:\Users\gojigoodra\Downloads\shinen-gax-python-main\libs\shinen_gax.py", line 729, in pack_instrument
    volenv_packed += pack_GAX_byte(self.volume_envelope["sustain_point"])
  File "C:\Users\gojigoodra\Downloads\shinen-gax-python-main\libs\shinen_gax.py", line 724, in pack_GAX_byte
    return val.to_bytes(1, signed=False)
TypeError: to_bytes() missing required argument 'byteorder' (pos 2)

Game used was The Polar Express

**Comment by beanieaxolotl** [comment]
...Huh.
On my end it seems to function perfectly:

![image](https://github.com/user-attachments/assets/fd596d66-120d-4d0d-b5f4-a13724dfdfde)

It could very well be a Python thing, as I developed these tools with Python 3.12.3 in mind.

**Comment by Bonboon229** [comment]
Which means I need to upgrade...
Let me try with that version

**Comment by Bonboon229** [comment]
All working as it should now!
